### ISSUE TITLE
tokens.h unnecessary 

### ISSUE THREAD

**Issue by carl-walker** [carl-walker/paxix#4]
Pretty sure after the paxi_parser.tab.h and paxi_parser.tab.c get created we no longer need tokens.h. Maybe just do a build without it and see if everything still works okay.

**Comment by thetinkeringtypist** [comment]
Do you guys have a Jenkins server set up for builds and tests?

**Comment by carl-walker** [comment]
No but we should set one up. Eric says we need to use Travis for github integration

**Comment by ewickert** [comment]
Resolved by 1404ca922371d19305fc6194f33dfbef7f804bf8
